---
platform: linux
inputs:
  - name: git-app
  - name: version
  - name: git-app-pipeline

outputs:
  - name: build-package-output

params:
  artifactory_path:
  artifactory_directory:
  artifactory_sub_directory:
  output_directory:

run:
  dir: git-app
  path: ../git-app-pipeline/ci/tasks/run-acl-build/aws-gov/task.sh
