---
  instance_limits:
    min: 1
    max: 6
  rules:
    - rule_type: "rabbitmq"
      rule_sub_type: "transform"
      threshold:
        min: 5000
        max: 20000     
  scheduled_limit_changes: []