---
platform: linux
inputs:
  -  name: git-app-pipeline

params:
    CF_API:
    CF_APP:
    CF_ORG:
    CF_PASSWORD:
    CF_SPACE:
    CF_USER:

run:
  dir: git-app-pipeline
  path: ci/tasks/bgd-clean-up/task.sh
  
