receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:9411
  zipkin:

exporters:
  datadog/api:
    env: region_name-space_name
    service: app_name
    tags:
      - segment:enterprise
      - product_family:capture
      - service:app_name
      - product:cloud_capture
      - feature:capture
      - customer:multicustomer
      - tier:space_name
      - cloud_provider:aws
      - cloud_region:region_name
      - service_region:oregon
      - service_team:engineering
      - component:application
      - foundation:aws-region_name
      - entity:multicustomer-oregon
      - namespace:cloud_capture_space_name
      - environment:multicustomer-oregon-cloud_capture_space_name
    api:
      key: datadog_key

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [datadog/api]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [datadog/api]
      processors: [batch]
