applications:
- name: tsfa-chat
  disk_quota: 1G
  env:
    JAVA_OPTS: -javaagent:/app/WEB-INF/lib/opentelemetry-javaagent-1.2.0.jar -Dsun.net.client.defaultReadTimeout=180000
    SPRING_PROFILES_INCLUDE: commercial
    JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{enabled: false}'
    SPRING_PROFILES_ACTIVE: cloud
    monitoring.tags.segment: enterprise
    monitoring.tags.product_family: capture
    monitoring.tags.service: tsfa-chat
    monitoring.tags.product: cloud_capture
    monitoring.tags.feature: capture
    monitoring.tags.customer: multicustomer
    monitoring.tags.tier: preprod
    monitoring.tags.cloud_provider: aws
    monitoring.tags.cloud_region: us_west_2
    monitoring.tags.service_region: oregon
    monitoring.tags.component: application
    monitoring.tags.foundation: aws-us_west_2
    monitoring.tags.entity: multicustomer-oregon
    monitoring.tags.namespace: cloud_capture-preprod
    monitoring.tags.environment: multicustomer-oregon-cloud_capture-preprod
    management.metrics.export.datadog.api-key: datadog_api_key
    transformer.broker.queueName: transform-chat
    transformer.broker.errorQueueName: transform-chat-error
    transformer.broker.threadCount: 50
    eureka.instance.appname: tsfa-chat
    eureka.client.enabled: true
  instances: 1
  memory: 2G
  routes:
  - route: tsfa-chat.cc.preprod.us-west-2.aws.smarsh.cloud
  services:
  - aws-s3-capture-service
  - eureka
  - app-log-drain
  - vault
  - aws-sqs-service
  - rmq_cluster_medium
  - autoscale-cc-preprod
  - pcc
  timeout: 180
