---
platform: linux
inputs:
  - name: git-app-target
  - name: git-app-pipeline

params:
  SONAR_URL:
  SONAR_PROJECT_KEY:
  SONAR_PROJECT_NAME:
  SONAR_TOKEN:
  sonar_quality_gate:

run:
  dir: git-app-target
  path: ../git-app-pipeline/ci/tasks/sonar-full-reposcan/task.sh
